// Auto-generated by scripts/gen-swift.js — do not edit by hand.
// Run `npm run gen:swift` to regenerate.
//
// Source of truth: tokens/tokens.json (v0.3.0).

import SwiftUI

/// Cathode design tokens — generated from tokens/tokens.json.
/// Use the `CathodeTheme` environment value to read the active
/// color set; spacing / type / size / motion are theme-independent.
public enum CathodeTokens {
    public enum Palette {
        public enum Dark {
        public static let bg: Color = Color(red: 0.0000, green: 0.0000, blue: 0.0000)
        public static let panel: Color = Color(red: 0.0706, green: 0.0706, blue: 0.0706)
        public static let border: Color = Color(red: 0.1804, green: 0.1804, blue: 0.1804)
        public static let text: Color = Color(red: 0.9176, green: 0.9176, blue: 0.9176)
        public static let textDim: Color = Color(red: 0.5216, green: 0.5216, blue: 0.5216)
        public static let textFaint: Color = Color(red: 0.2196, green: 0.2196, blue: 0.2196)
        public static let danger: Color = Color(red: 0.9216, green: 0.2392, blue: 0.2196)
        public static let dangerDeep: Color = Color(red: 0.7608, green: 0.1608, blue: 0.1490)
        public static let warning: Color = Color(red: 0.9490, green: 0.6196, blue: 0.2000)
        public static let success: Color = Color(red: 0.3490, green: 0.8196, blue: 0.4510)
        public static let info: Color = Color(red: 0.2196, green: 0.6588, blue: 0.8863)
        public static let accent: Color = Color(red: 0.9216, green: 0.4510, blue: 0.7804)
        public static let amber: Color = Color(red: 0.9490, green: 0.7569, blue: 0.2000)
        public static let pink: Color = Color(red: 0.9490, green: 0.4000, blue: 0.6784)
        public static let purple: Color = Color(red: 0.6980, green: 0.4510, blue: 0.9490)
        public static let teal: Color = Color(red: 0.2275, green: 0.8392, blue: 0.7804)
        public static let grey: Color = Color(red: 0.6196, green: 0.6471, blue: 0.7176)
        }
        public enum Light {
        public static let bg: Color = Color(red: 0.9647, green: 0.9686, blue: 0.9490)
        public static let panel: Color = Color(red: 0.9333, green: 0.9333, blue: 0.9059)
        public static let border: Color = Color(red: 0.7725, green: 0.7843, blue: 0.7490)
        public static let text: Color = Color(red: 0.1059, green: 0.1255, blue: 0.1882)
        public static let textDim: Color = Color(red: 0.3294, green: 0.3569, blue: 0.4196)
        public static let textFaint: Color = Color(red: 0.6902, green: 0.7059, blue: 0.6588)
        public static let danger: Color = Color(red: 0.7059, green: 0.1255, blue: 0.0980)
        public static let dangerDeep: Color = Color(red: 0.5412, green: 0.0784, blue: 0.0627)
        public static let warning: Color = Color(red: 0.6196, green: 0.3569, blue: 0.0745)
        public static let success: Color = Color(red: 0.1412, green: 0.4471, blue: 0.2078)
        public static let info: Color = Color(red: 0.1176, green: 0.4353, blue: 0.6588)
        public static let accent: Color = Color(red: 0.6510, green: 0.1961, blue: 0.4902)
        public static let amber: Color = Color(red: 0.4980, green: 0.3725, blue: 0.0627)
        public static let pink: Color = Color(red: 0.6118, green: 0.1569, blue: 0.4078)
        public static let purple: Color = Color(red: 0.3569, green: 0.1922, blue: 0.6510)
        public static let teal: Color = Color(red: 0.0588, green: 0.4314, blue: 0.3843)
        public static let grey: Color = Color(red: 0.3020, green: 0.3176, blue: 0.3765)
        }
    }

    public enum Spacing {
        public static let xs: CGFloat = 4
        public static let sm: CGFloat = 8
        public static let md: CGFloat = 12
        public static let lg: CGFloat = 16
        public static let xl: CGFloat = 24
        public static let xxl: CGFloat = 32
        public static let framePad: CGFloat = 12
        public static let rowHeight: CGFloat = 28
    }

    public enum Size {
        public static let pixelCell: CGFloat = 6
        public static let pixelSpacing: CGFloat = 2
        public static let tileCorner: CGFloat = 2
        public static let borderWidth: CGFloat = 1
        public static let borderWidthActive: CGFloat = 1.5
        public static let touchTargetMin: CGFloat = 44
        public static let iconSm: CGFloat = 12
        public static let iconMd: CGFloat = 16
        public static let iconLg: CGFloat = 22
    }

    public enum TypeScale {
        public static let caption: CGFloat = 9
        public static let readout: CGFloat = 11
        public static let label: CGFloat = 13
        public static let number: CGFloat = 16
        public static let display: CGFloat = 24
        public static let hero: CGFloat = 36
    }
    public enum Tracking {
        public static let header: CGFloat = 2
        public static let label: CGFloat = 1.4
        public static let caption: CGFloat = 0.8
    }
    public static let fontStack: String = "'JetBrains Mono', 'SF Mono', 'Menlo', 'Consolas', monospace"

    public enum MotionDuration {
        public static let instant: Double = 0.080
        public static let quick: Double = 0.150
        public static let settled: Double = 0.300
        public static let slow: Double = 0.500
    }
    public enum MotionScale {
        public static let press: CGFloat = 0.97
        public static let pop: CGFloat = 1.03
    }

    public enum Haptic {
        public static let tapMs: Int = 10
        public static let confirmMs: Int = 20
        public static let warnMs: [Int] = [10, 30, 10]
        public static let errorMs: [Int] = [20, 40, 20]
        public static let destructiveMs: Int = 35
        public static let longMs: Int = 40
    }

    public enum Breakpoint {
        public static let sm: CGFloat = 480
        public static let md: CGFloat = 768
        public static let lg: CGFloat = 1024
        public static let xl: CGFloat = 1280
    }
}
