#!/usr/bin/env node
// Generates packages/swift/Sources/CathodeUI/Tokens.swift from
// tokens/tokens.json. Emits SwiftUI-ready Color values for both
// themes plus theme-independent type / spacing / size / motion /
// haptic constants.
//
// Output namespace:
//   public enum CathodeTokens {
//     public enum Color { public enum Dark { static let bg: Color = ... } }
//     public enum Spacing { static let md: CGFloat = 12 }
//     public enum Type { static let label: CGFloat = 13 }
//     ...
//   }

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const TOKENS = JSON.parse(readFileSync(resolve(ROOT, 'tokens/tokens.json'), 'utf8'));
const OUT = resolve(ROOT, 'packages/swift/Sources/CathodeUI/Tokens.swift');

const HEADER = `// Auto-generated by scripts/gen-swift.js — do not edit by hand.
// Run \`npm run gen:swift\` to regenerate.
//
// Source of truth: tokens/tokens.json (v${TOKENS.version}).
`;

/** "#RRGGBB" → SwiftUI Color literal. */
function hexToColor(hex) {
  const m = hex.match(/^#([0-9a-fA-F]{6})$/);
  if (!m) throw new Error(`bad hex: ${hex}`);
  const n = parseInt(m[1], 16);
  const r = ((n >> 16) & 0xff) / 255;
  const g = ((n >> 8) & 0xff) / 255;
  const b = (n & 0xff) / 255;
  return `Color(red: ${r.toFixed(4)}, green: ${g.toFixed(4)}, blue: ${b.toFixed(4)})`;
}

/** TitleCase for nested namespace keys. */
function pascal(s) {
  return s[0].toUpperCase() + s.slice(1);
}

function colorBlock(theme) {
  const set = TOKENS.color[theme];
  const lines = [];
  for (const [key, hex] of Object.entries(set)) {
    lines.push(`        public static let ${key}: Color = ${hexToColor(hex)}`);
  }
  return lines.join('\n');
}

function scalarBlock(obj) {
  const lines = [];
  for (const [key, value] of Object.entries(obj)) {
    if (typeof value === 'number') {
      lines.push(`        public static let ${key}: CGFloat = ${value}`);
    } else if (typeof value === 'string') {
      // String values inside numeric groups (e.g. ease curves) — keep as String.
      lines.push(`        public static let ${key}: String = ${JSON.stringify(value)}`);
    }
    // Arrays + nested objects skipped here; emit them in dedicated blocks below.
  }
  return lines.join('\n');
}

const out = [];
out.push(HEADER);
out.push('import SwiftUI');
out.push('');
out.push('/// Cathode design tokens — generated from tokens/tokens.json.');
out.push('/// Use the `CathodeTheme` environment value to read the active');
out.push('/// color set; spacing / type / size / motion are theme-independent.');
out.push('public enum CathodeTokens {');

// Color — namespaced as `Palette` so the inner `Color` literals
// reference SwiftUI.Color rather than self-shadowing this enum.
out.push('    public enum Palette {');
out.push('        public enum Dark {');
out.push(colorBlock('dark'));
out.push('        }');
out.push('        public enum Light {');
out.push(colorBlock('light'));
out.push('        }');
out.push('    }');
out.push('');

// Spacing
out.push('    public enum Spacing {');
out.push(scalarBlock(TOKENS.spacing));
out.push('    }');
out.push('');

// Size
out.push('    public enum Size {');
out.push(scalarBlock(TOKENS.size));
out.push('    }');
out.push('');

// Type — scale + tracking + weight (weights become Font.Weight elsewhere; emit raw numbers)
out.push('    public enum TypeScale {');
out.push(scalarBlock(TOKENS.type.scale));
out.push('    }');
out.push('    public enum Tracking {');
out.push(scalarBlock(TOKENS.type.tracking));
out.push('    }');
out.push('    public static let fontStack: String = ' + JSON.stringify(TOKENS.type.fontStack));
out.push('');

// Motion — duration in ms; consumers convert to TimeInterval (seconds)
out.push('    public enum MotionDuration {');
for (const [key, ms] of Object.entries(TOKENS.motion.duration)) {
  out.push(`        public static let ${key}: Double = ${(ms / 1000).toFixed(3)}`);
}
out.push('    }');
out.push('    public enum MotionScale {');
out.push(scalarBlock(TOKENS.motion.scale));
out.push('    }');
out.push('');

// Haptic — UIImpactFeedbackGenerator-friendly raw intensity values.
// Web stack uses navigator.vibrate(ms) durations; iOS uses styles
// (light/medium/heavy/rigid/soft). We expose both: the raw ms (for
// consumers that prefer to drive their own logic) and a recommended
// UIImpactFeedbackGenerator.FeedbackStyle as a string the runtime
// adapter maps to the actual enum.
out.push('    public enum Haptic {');
for (const [key, value] of Object.entries(TOKENS.haptic)) {
  if (typeof value === 'number') {
    out.push(`        public static let ${key}Ms: Int = ${value}`);
  } else if (Array.isArray(value)) {
    out.push(`        public static let ${key}Ms: [Int] = [${value.join(', ')}]`);
  }
}
out.push('    }');
out.push('');

// Breakpoint (size-class hints; consumers use Swift's own GeometryReader / size classes)
out.push('    public enum Breakpoint {');
out.push(scalarBlock(TOKENS.breakpoint));
out.push('    }');

out.push('}');
out.push('');

writeFileSync(OUT, out.join('\n'));
console.log(`Wrote ${OUT}`);
