#!/usr/bin/env node
// Generates packages/react/src/tokens.css from tokens/tokens.json.
//
// Output strategy:
//   :root { light tokens }
//   @media (prefers-color-scheme: dark) { :root { dark tokens } }
//
// Light is the default so there's no flash of dark content before media
// queries evaluate on light-mode devices. Apps can force a theme by
// setting `data-theme="dark"` on <html> or any ancestor.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const TOKENS = JSON.parse(readFileSync(resolve(ROOT, 'tokens/tokens.json'), 'utf8'));
const OUT = resolve(ROOT, 'packages/react/src/tokens.css');

const HEADER = `/* Auto-generated by scripts/gen-css.js — do not edit by hand. */
/* Run \`npm run gen:css\` to regenerate. */`;

/**
 * Flatten an object into CSS custom-property lines.
 * { color: { text: "#000" } } -> ["--cathode-color-text: #000;"]
 */
function toVars(obj, prefix = '--cathode') {
  const lines = [];
  for (const [key, value] of Object.entries(obj)) {
    const varName = `${prefix}-${kebab(key)}`;
    if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
      lines.push(...toVars(value, varName));
    } else if (Array.isArray(value)) {
      // Arrays (e.g. haptic.error = [20,40,20]) go in as comma strings —
      // JS consumers parse; CSS ignores. Included for completeness.
      lines.push(`  ${varName}: ${value.join(',')};`);
    } else if (typeof value === 'number') {
      // Dimensions default to px; callers cast to rem elsewhere if needed.
      const needsUnit = !isUnitless(varName);
      lines.push(`  ${varName}: ${value}${needsUnit ? 'px' : ''};`);
    } else {
      lines.push(`  ${varName}: ${value};`);
    }
  }
  return lines;
}

function kebab(s) {
  return s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

/** Keys whose values are naturally unitless.
 *
 * We can't just match substrings because `type-scale-*` (font sizes,
 * need `px`) and `motion-scale-*` (multipliers, unitless) both contain
 * "scale". So we match by full prefix path instead.
 */
function isUnitless(varName) {
  const unitlessPrefixes = [
    '--cathode-type-weight',     // 400, 600, etc.
    '--cathode-type-tracking',   // letter-spacing multiplier
    '--cathode-motion-duration', // milliseconds — callers append `ms`
    '--cathode-motion-scale',    // transform multipliers (0.97, 1.03)
    '--cathode-sound',           // freq/ms/gain — JS-side only
    '--cathode-haptic',          // ms durations — JS-side only
  ];
  return unitlessPrefixes.some((p) => varName.startsWith(p));
}

const commonLines = [
  '/* Typography, spacing, size, motion, sound, haptic — theme-independent */',
  ...toVars(TOKENS.type,       '--cathode-type'),
  ...toVars(TOKENS.spacing,    '--cathode-space'),
  ...toVars(TOKENS.size,       '--cathode-size'),
  ...toVars(TOKENS.motion,     '--cathode-motion'),
  ...toVars(TOKENS.sound,      '--cathode-sound'),
  ...toVars(TOKENS.haptic,     '--cathode-haptic'),
  ...toVars(TOKENS.breakpoint, '--cathode-bp'),
];

const lightLines = toVars(TOKENS.color.light, '--cathode-color');
const darkLines = toVars(TOKENS.color.dark, '--cathode-color');

const css = `${HEADER}

:root {
  /* Light theme is the default; see @media below for dark override. */
${lightLines.join('\n')}

${commonLines.join('\n')}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${darkLines.join('\n')}
  }
}

[data-theme="dark"] {
${darkLines.join('\n')}
}

[data-theme="light"] {
${lightLines.join('\n')}
}
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, css);
console.log(`Wrote ${OUT}`);
